TOPUS/urls.py
from django.urls import path, include
from django.contrib import admin

from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('', include('products.urls')),
    path('api/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'utils.errors.handler403'
handler404 = 'utils.errors.handler404'

cart/urls.py
from django.urls import path
from cart.views import CartAPI, CheckCartAPI, AcceptCartAPI


urlpatterns = [
    path('', CartAPI.as_view(), name='cart'),
    path('check_order', CheckCartAPI.as_view(), name='check_order'),
    path('accept_order', AcceptCartAPI.as_view(), name='accept_order'),

]

products/urls.py
from rest_framework.routers import SimpleRouter
from django.conf.urls.static import static
from django.conf import settings
from relations.views import AdToFavAPI, SearchViewSet, Main
from products.views import ClothviewSet, GamingViewSet, HomeViewSet

from django.urls import path

router = SimpleRouter()
router.register(r'cloth', ClothviewSet, basename='cloth')
router.register(r'gaming', GamingViewSet, basename='gaming')
router.register(r'for_home', HomeViewSet, basename='for_home')


urlpatterns = [
    path('', Main.as_view(), name='home'),
    path('search/', SearchViewSet.as_view(), name='search'),
    path('add_to_fav/<int:pk>', AdToFavAPI.as_view(), name='add_to_fav'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += router.urls

products/models.py
from django.urls import reverse
from django.db import models
from relations.models import Relation
from users.models import User


class Category(models.Model):
    """Модель  категорій
    """
    cat_name = models.CharField('Назва', max_length=100)
    slug = models.SlugField('URL', max_length=100, unique=True,
                            db_index=True)
    main_image = models.ImageField('фото',
                                   upload_to='category_photo', default='../static/images/no-image-icon.png')

    def __str__(self):
        return self.cat_name

    class Meta:
        verbose_name = 'Категорію'
        verbose_name_plural = 'Категорії'

    def get_absolute_url(self):
        return reverse('', kwargs={'cat_slug': self.slug})


class MainModel(models.Model):
    """Головна модель
    """
    title = models.CharField('Назва', max_length=60)
    description = models.TextField('Опис', blank=True)
    price = models.DecimalField('Вартість', max_digits=7, decimal_places=2)
    brand = models.CharField('Бренд', max_length=50, blank=True)
    main_image = models.ImageField('Головне фото',
                                   upload_to='main_photo', default='../static/images/no-image-icon.png')
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Категорія')
    s_code = models.CharField(
        'Код', max_length=10, unique=True, blank=True)
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, verbose_name='Власник', related_name='create')
    date_created = models.DateTimeField(
        auto_now_add=True, verbose_name='Час створення')
    discount = models.SmallIntegerField(
        default=0, verbose_name='Знижка')  # 0-100%
    is_published = models.BooleanField('Публікація',
                                       default=False)
    viewed = models.ManyToManyField(
        User, through=Relation, related_name='view')
    rating = models.DecimalField(
        max_digits=2, decimal_places=1, default=0, null=True, verbose_name='Рейтинг')  # кэшуюче поле
    in_liked = models.ManyToManyField(
        User, related_name='in_favourite', blank=True)

    def __str__(self) -> str:
        return f'Id {self.id}: {self.title}'

    def get_absolute_url(self):
        return reverse(f'{self.category.slug}-detail', args=(self.id,))


class Clothes(MainModel):
    """Модель одягу
    """

    SIZE = (
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL')
    )
    SEASON = (
        ('Все сезон', 'Все сезон'),
        ('Літо', 'Літо'),
        ('Осінь', 'Осінь'),
        ('Зима', 'Зима'),
        ('Весна', 'Весна'),
    )

    DEPART = (
        ('Жіноча', 'Жіноча'),
        ('Чоловіча', 'Чоловіча'),
        ('Унісекс', 'Унісекс'),
    )

    size = models.CharField('Розмір', max_length=2, choices=SIZE, blank=True)
    season = models.CharField('Сезон', max_length=11,
                              choices=SEASON, blank=True)

    department = models.CharField('Стать', choices=DEPART, blank=True)

    class Meta:
        verbose_name = 'Одяг'
        verbose_name_plural = 'Одяг'

    def __str__(self) -> str:
        return f'Id {self.id}: {self.title}'

    def get_absolute_url(self):
        return reverse('cloth-detail', args=(self.id,))


class Gaming(MainModel):
    """Модель ігрової переферії
    """
    material = models.CharField('Матеріал',
                                max_length=50, blank=True)
    model = models.CharField('Модель',
                             max_length=50, blank=True)
    color = models.CharField('Колір', max_length=15, blank=True)

    class Meta:
        verbose_name = 'Ігрова переферія'
        verbose_name_plural = 'Ігрова переферія'

    def __str__(self) -> str:
        return f'Id {self.id}: {self.title}'

    def get_absolute_url(self):
        return reverse('gaming-detail', args=(self.id,))


class Home(MainModel):
    """Модель товарів для дому
    """
    material = models.CharField('Матеріал', max_length=50, blank=True)
    color = models.CharField('Колір', max_length=15, blank=True)
    room_type = models.CharField('Для кімнат', max_length=50, blank=True)
    weight = models.DecimalField(
        'Вага', max_digits=5, decimal_places=1, blank=True)
    dimensions = models.CharField(
        'Розмір(ВхШхГ), см', max_length=30, blank=True)

    class Meta:
        verbose_name = 'Для дому'
        verbose_name_plural = 'Для дому'

    def __str__(self) -> str:
        return f'Id {self.id}: {self.title}'

    def get_absolute_url(self):
        return reverse('for_home-detail', args=(self.id,))


class Gallery_cloth(models.Model):
    """Модель декількох фото 'одягу' до 1-го об'єкту
    """
    images = models.ImageField('Фото', upload_to='cloth_photos')
    clothes_id = models.ForeignKey(
        'Clothes', verbose_name='cloth_photo', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Фото товару'
        verbose_name_plural = 'Фото товару'


class Gallery_gaming(models.Model):
    """Модель декількох фото "ігрової переферії" до 1-го об'єкту
    """
    images = models.ImageField('Фото', upload_to='gaming_photo')
    gaming_id = models.ForeignKey(
        'Gaming', verbose_name='gaming_photo', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Фото товару'
        verbose_name_plural = 'Фото товару'


class Gallery_home(models.Model):
    """Модель декількох фото категорії "для дому" до 1-го об'єкту
    """
    images = models.ImageField('Фото', upload_to='home_photo')
    home_id = models.ForeignKey(
        'Home', verbose_name='home_photo', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Фото товару'
        verbose_name_plural = 'Фото товару'

relations/models.py
from django.urls import reverse
from django.db import models
from users.models import User


class Relation(models.Model):
    """Модель відношень користувача та товару
    """

    RATING = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Юзер')
    item = models.ForeignKey(
        'products.MainModel', on_delete=models.CASCADE, verbose_name='об\'єкт', related_name='rati')
    rate = models.PositiveSmallIntegerField(
        'Оцінка', choices=RATING, default=None, blank=True, null=True)
    comment = models.TextField(
        'Коментарій', max_length=3000, null=True, blank=True)
    parent = models.ForeignKey(
        'self', verbose_name='Відповідь на відгук', on_delete=models.CASCADE, blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = "Зв'язок"
        verbose_name_plural = "Зв'язок"
        ordering = ['-created_at']

    def __str__(self) -> str:
        parent_str = f" & {self.parent}" if self.parent else ""
        return f'{self.id}) {self.user.username} -> {self.item.title}{parent_str}'

    def __init__(self, *args, **kwargs):
        super(Relation, self).__init__(*args, **kwargs)
        self.old_rate = self.rate

    def save(self, *args, **kwargs):
        creating = not self.pk
        super().save(*args, **kwargs)
        if self.old_rate != self.rate or creating:
            from products.utils import set_rating
            set_rating(self.item)

    def get_absolute_url(self):
        return reverse(self.item, args=(self.item.id,))

products/views.py
from rest_framework.authentication import SessionAuthentication
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework import renderers
from django_filters.rest_framework import DjangoFilterBackend
from django.contrib.messages import get_messages
from django.db.models import F, Count, Q, Prefetch
from products.serializers import ClothSerializer, HomeSerializer, GamingSerializer
from products.models import Clothes, Gaming, Home, Gallery_cloth, Gallery_gaming, Gallery_home
from products.utils import serial_code_randomizer, ProductPriceFilter
from relations.models import Relation
from relations.utils import accept_post
from utils.pagination import Pagination
from users.permission import IsAdminOrReadOnly
from users.models import User
from cart.views import Cart

price_with_discount = F('price') - F('price') / 100 * F('discount')


class BaseItemViewSet(ModelViewSet):
    """ Базова view для моделей
    Args:
        list: повертає сторінку зі списком товарів за категорією
        retrieve: повертає сторінку товару

    Returns:
        Response
    """
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = ProductPriceFilter
    permission_classes = [IsAdminOrReadOnly]
    ordering_fields = ['price_w_dis', 'date_created', 'rating']
    ordering = ['-date_created']
    renderer_classes = (renderers.JSONRenderer, renderers.TemplateHTMLRenderer)
    authentication_classes = [SessionAuthentication]
    pagination_class = Pagination

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user,
                        s_code=serial_code_randomizer(serializer.validated_data['category']))

    def post(self, request, pk):
        request, parametrs = accept_post(self, request, pk)

        response = super(BaseItemViewSet, self).retrieve(request, pk)
        images = self.get_gallery_objects(pk)
        relation = Relation.objects.select_related(
            'item', 'user').filter(parent__isnull=True, item_id=pk).only('item__id', 'user__id', 'rate', 'comment', 'user__username', 'parent__id', 'id')
        answer = Relation.objects.select_related(
            'item', 'user').filter(parent__isnull=False, item_id=pk).only('item__id', 'user__id', 'rate', 'comment', 'user__username', 'parent__id', 'id')
        data_info = self.get_additional_info(response.data)
        in_cart = True if pk in Cart(request).cart else False

        # якщо це зміна існуючого відгуку, то блокується кнопка "надіслати"
        for message in get_messages(request):
            if message.extra_tags == '1':
                parametrs['accept'] = False

        return Response({'data': response.data, 'images': images, 'relation': relation, 'answer': answer, 'parametrs': parametrs, 'info': data_info, 'in_cart': in_cart}, template_name='item_view.html')

    def list(self, request, *args, **kwargs):
        response = super(BaseItemViewSet, self).list(request, *args, **kwargs)
        if request.accepted_renderer.format == 'html':
            return Response({'data': response.data}, template_name='list_item_page.html')
        return response

    def retrieve(self, request, pk=None):
        response = super(BaseItemViewSet, self).retrieve(request, pk)
        if request.accepted_renderer.format == 'html':
            images = self.get_gallery_objects(pk)
            relation = Relation.objects.select_related(
                'item', 'user').filter(parent__isnull=True, item_id=pk).only('item__id', 'user__id', 'rate', 'created_at', 'comment', 'user__username', 'id')
            answer = Relation.objects.select_related(
                'item', 'user').filter(parent__isnull=False, item_id=pk).only('item__id', 'user__id', 'rate', 'comment', 'user__username', 'parent__id', 'id')
            data_info = self.get_additional_info(response.data)
            parametrs = {'accept': True}
            in_cart = True if pk in Cart(request).cart else False
            return Response({'data': response.data, 'images': images, 'relation': relation, 'answer': answer, 'parametrs': parametrs, 'info': data_info, 'in_cart': in_cart}, template_name='item_view.html')
        return response

    def get_gallery_objects(self, pk):
        raise NotImplementedError('Метод для дітей :)')

    def get_additional_info(self, data):
        raise NotImplementedError('Метод для дітей :)')


class ClothviewSet(BaseItemViewSet):
    queryset = Clothes.objects.all().prefetch_related(Prefetch('in_liked', queryset=User.objects.all().only('id'))).filter(
        is_published=True).annotate(price_w_dis=price_with_discount, views=Count('viewed', filter=Q(rati__rate__in=(1, 2, 3, 4, 5))))
    serializer_class = ClothSerializer

    def get_gallery_objects(self, pk):
        return Gallery_cloth.objects.filter(clothes_id=pk)

    def get_additional_info(self, data):
        return {
            'Пора року': data['season'] if data['season'] else '-',
            'Для кого': data['department'] if data['department'] else '-',
            'Розмір': data['size'] if data['size'] else '-'
        }


class GamingViewSet(BaseItemViewSet):
    queryset = Gaming.objects.all().prefetch_related(Prefetch('in_liked', queryset=User.objects.all().only('id'))).filter(
        is_published=True).annotate(price_w_dis=price_with_discount, views=Count('viewed', filter=Q(rati__rate__in=(1, 2, 3, 4, 5))))
    serializer_class = GamingSerializer

    def get_gallery_objects(self, pk):
        return Gallery_gaming.objects.filter(gaming_id=pk)

    def get_additional_info(self, data):
        return {
            'Модель': data['model'] if data['model'] else '-',
            'Матеріал': data['material'] if data['material'] else '-',
            'Колір': data['color'] if data['color'] else '-'
        }


class HomeViewSet(BaseItemViewSet):
    queryset = Home.objects.all().prefetch_related(Prefetch('in_liked', queryset=User.objects.all().only('id'))).filter(
        is_published=True).annotate(price_w_dis=price_with_discount, views=Count('viewed', filter=Q(rati__rate__in=(1, 2, 3, 4, 5))))
    serializer_class = HomeSerializer

    def get_gallery_objects(self, pk):
        return Gallery_home.objects.filter(home_id=pk)

    def get_additional_info(self, data):
        return {
            'Для кімнат': data['room_type'] if data['room_type'] else '-',
            'Матеріал': data['material'] if data['material'] else '-',
            'Колір': data['color'] if data['color'] else '-',
            'Вага': str(data['weight']) + ' кг' if data['weight'] else '-',
            'Розмір(ВхШхГ), см': data['dimensions'] if data['dimensions'] else '-',
        }

products/templates/cloth.html
{% extends "base.html" %}

{% block content %}
<p>CLOTH</p>

<ul>
    {% for item in data %}
    {% if item.main_image %}
    <p><img src="{{ item.main_image }}" width="300 300"></p>
    {% endif %}
    <a href="{{ item.id }}">
        <p>{{ item.title }}</p>
    </a>
    <ul>Ціна: {{ item.price }}</ul>
    {% if item.discount is not 0 %}
    <ul>Знижка: {{ item.discount }}%</ul>
    <ul>Ціна зі знижкою: {{ item.price_w_dis }}</ul>
    {% endif %}

    <ul>Рейтинг {{item.rating}}</ul>

    {% endfor %}
    {% for image in data.gallery_cloth_set %}
    <p>image</p>
    {% endfor %}
</ul>
{% endblock %}

products/templates/item_page.html
{% extends "base.html" %}

{% block content %}

<ul>
    {% for item in data %}
    {% if item.main_image %}
    <p><img src="{{ item.main_image }}" width="300 300"></p>
    {% endif %}
    <a href="{{ item.id }}">
        <p>{{ item.title }}</p>
    </a>
    <ul>Ціна: {{ item.price }}</ul>
    {% if item.discount is not 0 %}
    <ul>Знижка: {{ item.discount }}%</ul>
    <ul>Ціна зі знижкою: {{ item.price_w_dis }}</ul>
    {% endif %}

    <ul>Рейтинг {{item.rating}}</ul>

    {% endfor %}
    {% for image in data.gallery_cloth_set %}
    <p>image</p>
    {% endfor %}
</ul>
{% endblock %}

products/templates/list_cate.html
<div class="products-container">
    {% for c in cats %}

    <div class="card">
        <a href="{{ c.slug }}" class="card__content">
            <img src="{{ c.main_image.url }}" alt="{{c.cat_name}}">
            <div class="card__text">{{c.cat_name}}</div>
        </a>
    </div>

    {% endfor %}
</div>

products/templates/list_item_page.html
{% extends "base.html" %}
{% load static %}
{% load tags %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/slider-price.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_list_cate_item.css' %}">
</head>

<div class="produce_section">
    <!-- Ordering -->
    <div class="hid">
        <div class="catalog-settings">
            <form method="get" id="orderForm">
                <select class="select-css" id="orderSelect" name="ordering" onchange="applyOrdering()">
                    <option name="new" value="-date_created" onclick="applyOrdering()">Новинки</option>
                    <option name="price" value="price_w_dis" onclick="applyOrdering()">Від дешевих до дорогих</option>
                    <option name="-price" value="-price_w_dis" onclick="applyOrdering()">Від дорогих до дешевих</option>
                    <option name="rate" value="-rating" onclick="applyOrdering()">За рейтингом</option>
                </select>
            </form>
            <!-- Ordering price -->
            <form id="PriceOrdering">
                <div id="slider"></div>
                <div class="or_in_pr">
                    <input name="min_price" class="in_pr" type="text" id="input-with-keypress-0" value="" pattern="\d*">
                    -
                    <input name="max_price" class="in_pr" type="text" id="input-with-keypress-1" value="" pattern="\d*">
                </div>
                <div class="btn_ord_price">
                    <button class="btn btn-info" type="submit">Ок</button>
                </div>
            </form>
            <!--\ Orering price -->
        </div>
    </div>
    <!--\ Ordering -->

    <div class="list-container">
        {% for item in data.results %}
        <a href="{{ item.absolute_url }}">
        <div class="product-card">
            <!-- збережене -->
            <div class="to_fav">
                {% if request.user.is_anonymous %}
                <!-- анонім -->
                {% if item.id in request.session.favourite_products %}
                <button class="heart-btn" style="color: #ff8d02;" id="{{ item.id }}"><i value="{{ item.id }}"
                        class="fa-solid fa-heart fa-lg"></i></button>
                {% else %}
                <button class="heart-btn" style="color: #ff8d02;" id="{{ item.id }}"><i value="{{ item.id }}"
                        class="fa-regular fa-heart fa-lg"></i></button>
                {% endif %}
                <!--\ анонім -->

                {% else %}
                <!-- авторизований юзер -->
                {% if request.user.id in item.in_liked %}
                <button class="heart-btn" style="color: #ff8d02;" id="{{ item.id }}"><i value="{{ item.id }}"
                        class="fa-solid fa-heart fa-lg"></i></button>
                {% else %}
                <button class="heart-btn" style="color: #ff8d02;" id="{{ item.id }}"><i value="{{ item.id }}"
                        class="fa-regular fa-heart fa-lg"></i></button>
                {% endif %}
                <!--\ авторизований юзер -->
                {% endif %}
            </div>
            <!--\ збережене -->

            <img src="{{ item.main_image }}" alt="Фото" class="product-image">
            <h2 class="product-title">{{ item.title|truncatechars:50 }}</h2>
            <p class="product-description">Бренд: {{ item.brand }}</p>
            {% if item.discount is not 0 %}
            <div class="discount">
                <div class="product-discount">Знижка: {{ item.discount }} %</div>
                <div class="product-original-price"><del>{{ item.price|floatformat:"g" }} грн</del></div>
            </div>
            <p class="product-discounted-price">{{ item.price_w_dis|floatformat:"g" }} грн</p>
            {% else %}
            <p class="product-discounted-price">{{ item.price|floatformat:"g" }} грн</p>
            {% endif %}
            <div class="container_rat">
                <div class="rating">
                    <div class="rating__body">
                        <div class="rating__active"></div>
                        <div class="rating__items">
                            <input type="radio" name="rating" class="rating__item" value="1">
                            <input type="radio" name="rating" class="rating__item" value="2">
                            <input type="radio" name="rating" class="rating__item" value="3">
                            <input type="radio" name="rating" class="rating__item" value="4">
                            <input type="radio" name="rating" class="rating__item" value="5">
                        </div>
                    </div>
                    <div hidden class="rating__value">{{ item.rating }}</div>
                </div>
            </div>
            <div class="P_otziv">Відгуків: {{ item.views }}</div>
        </div>
    </a>
        {% empty %}

        <head>
            <link rel="stylesheet" href="{% static 'css/errors.css' %}">
        </head>

        <div class="error-container">
            <div class="image-container">
                <img id="alert_img" class="error-image" src="{% static 'images/404.png' %}" alt="Error 404" width="400">
            </div>
            <p id="alert_text" class="text">{{ message }}</p>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'js/slider-price.js' %}"></script>
<script src="{% static 'js/list_item.js' %}"></script>
{% endblock %}

products/templates/main_page.html
{% extends "base.html" %}
{% load tags %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/st_category.css' %}">
    <title>TOPUS-shop</title>
</head>

{% show_categories %}

{% endblock %}

products/templates/view_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/st_category2.css' %}">
</head>

{% include 'include/messages.html' %}
<div class="product-page">
    <div class="product-image">
        <p><img id="largeImg" src="{{ data.main_image }}" alt="Large image"></p>

        <div id="thumbs">
            {% for image in images %}
            <a href="{{ image.images.url }}"><img src="{{ image.images.url }}"></a>
            {% endfor %}
        </div>
    </div>
    <div class="product-description">
        <h1>{{ data.title }}</h1>
        <div class="product-details">
            <div class="product-detail">
                <span class="left">Ціна:</span>
                <span class="right">{{ data.price }} грн</span>
            </div>
            <!-- discount -->
            {% if data.discount > 0 %}
            <div class="product-detail">
                <span class="left">Знижка:</span>
                <span class="right">{{ data.discount }} %</span>
            </div>
            <div class="product-detail">
                <span class="left">Ціна зі знижкою:</span>
                <span class="right">{{ data.price_w_dis }} грн</span>
            </div>
            {% endif %}
            <!-- \ discount -->
            <div class="product-detail">
                <span class="left">Бренд:</span>
                <span class="right">{{ data.brand }}</span>
            </div>
            <div class="product-detail">
                <span class="left">Рейтинг:</span>
                <span class="right">{% if data.rating is None %} Немає оцінок {% else %} {{ data.rating }} {% endif %}</span>
            </div>
            {% for key, value in info.items %}
            <div class="product-detail">
                <span class="left">{{ key }}:</span>
                <span class="right">{{ value }}</span>
            </div>
            {% endfor %}
            <div class="product-detail">
                <span class="left">Код:</span>
                <span class="right">{{ data.s_code }}</span>
            </div>
            <div class="product-detail">
                <span class="left">Дата створення:</span>
                <span class="right">{{ data.date_created }}</span>
            </div>
        </div>

        <div class="buy">
            <!-- auth -->
            {% if request.user.is_authenticated %}
            <!-- in liked -->
                {% if request.user.id in data.in_liked %}
                <div class="add_to_fav">
                    <button class="button_view_page" style="color: #ff0080;" value="{{ data.id }}"><i value="{{ data.id }}"
                            id='to_fav' class="fa-solid fa-heart fa-lg"></i></button>
                </div>
                {% else %}
                <div class="add_to_fav">
                    <button class="button_view_page" style="color: #ff0080;" value="{{ data.id }}"><i value="{{ data.id }}"
                            id="to_fav" class="fa-regular fa-heart fa-lg"></i></button>
                </div>
                {% endif %}
                <!-- \ in liked -->
            {% else %}
            <div class="add_to_fav">
                <button disabled class="button_view_page" style="color: #ff0080;" value="{{ data.id }}"><i
                        value="{{ data.id }}" id="to_fav" class="fa-regular fa-heart fa-lg"></i></button>
            </div>
            {% endif %}
            <!-- \ auth -->

            <div class="add_to_cart_btn">
                <button value="{{ data.id }}" class="button_view_page">Придбати</button>
            </div>
        </div>

    </div>
</div>

<h2>Опис:</h2>
<p class="description">{{ data.description|linebreaksbr }}</p>
<!--  написати відгук -->
<div class="add-review">
    <h2>Напишіть свій відгук:</h2>
    <form method="post" id="review-form">
        {% csrf_token %}
        <div class="ralative">
            <div class="rating">
                <input value="5" name="rate" id="star5" type="radio">
                <label for="star5"></label>
                <input value="4" name="rate" id="star4" type="radio">
                <label for="star4"></label>
                <input value="3" name="rate" id="star3" type="radio">
                <label for="star3"></label>
                <input value="2" name="rate" id="star2" type="radio">
                <label for="star2"></label>
                <input value="1" name="rate" id="star1" type="radio">
                <label for="star1"></label>
            </div>
        </div>
        {% if request.user.is_authenticated and parametrs.accept is True %}
        <textarea rows="4" cols="50" name="comment" id="contactcomment">{{ parametrs.comment }}</textarea>
        <button type="submit" class="button_view_page">
            Надіслати
        </button>
        {% else %}
        <textarea rows="4" cols="50" name="comment" id="contactcomment" disabled>{{ parametrs.comment }}</textarea>
        <button disabled type="submit" class="button_view_page">
            Надіслати
        </button>
        {% endif %}
    </form>
</div>
<!-- \ написати відгук -->



<!-- Відгуки -->
<div class="reviews">
    <!-- Відгук  -->
    {% for review in relation %}
    <div class="review">
        <p>Дата: {{ review.created_at|date:"d E Y" }}</p>
        <h4>Юзер: {{ review.user.username }}</h4>
        <div class="rating">Оцінка: <span>{{ review.rate }}</span></div>
        <p class="review-text">Текст: {{ review.comment }}</p>

        {% if review.user.id is request.user.id %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" style="margin: 5px;">Видалити</button>
            <input type="hidden" name="delete_relation" value="{{review.id}}">
        </form>
        {% endif %}

        {% if request.user.is_staff %}
        <div class="answer" >
            <button class="btn btn-primary" style="margin: 5px;" value="{{ review.user.username }},{{ review.id }}">Відповісти</button>
            <form method="post" style="margin: 5px; display: none;" >
                {% csrf_token %}
                <textarea name="comment" id="answer_text" width="10"></textarea>
                <button class="btn btn-success" id="answer_id" name="parent" value="">Відправити</button>
            </form>
        </div>
            {% endif %}

        <!-- Відповіді на відгук -->
        {% for ans in review.relation_set.all %}
        <!-- <br> -->
        <div class="ans-for-review">
            <p>{{ ans.user.username }} відповів {{ review.user.username }}</p>
            <p>{{ ans.comment }}</p>
        </div>
            {% if ans.user.id is request.user.id %}
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" style="margin: 5px;">Видалити відповідь</button>
                <input type="hidden" name="delete_relation" value="{{ans.id}}">
            </form>
            {% endif %}
        {% endfor %}
        <!-- \ Відповіді на відкуг -->
    </div>
    {% endfor %}
    <!-- \ Відгук -->
</div>
<!-- \ Відгуки -->

<script src="{% static 'js/item_view.js' %}"></script>
{% endblock %}